name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - release    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Dotnet Publish
      run: dotnet publish . -c Release -o deploy
    - name: Copy files via ssh rsync
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
        RSYNC_TARGET: ${{ secrets.REMOTE_TARGET }}
        RSYNC_SOURCE: /home/runner/work/Thin-Blue-Lie/Thin-Blue-Lie/deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        SSH_USERNAME: ${{ secrets.REMOTE_USER }}
        SSH_HOSTNAME: ${{ secrets.REMOTE_HOST }}   
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl restart thin-blue-lie
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Discord Notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        username: Deployments
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        description: 'Deployment: ${{ job.status }}'
        details: '${{ github.actor }}: ${{ github.event_name }}'
        footer: ${{ github.workflow }}
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}