name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - release    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Dotnet Publish
      run: dotnet publish . -c Release -o deploy
    - name: Copy files via ssh rsync
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*' --exclude 'appsettings.*'
        RSYNC_TARGET: ${{ secrets.REMOTE_TARGET }}
        RSYNC_SOURCE: /deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        SSH_USERNAME: ${{ secrets.REMOTE_USER }}
        SSH_HOSTNAME: ${{ secrets.REMOTE_HOST }}   
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl restart thin-blue-lie
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deployment Success
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ success() }}
      with:
        severity: info
        details: Deployment Succeeded!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Deployment Failure
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ failure() }}
      with:
        severity: error
        details: Deployment Failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Deployment Cancelled
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ cancelled() }}
      with:
        severity: warn
        details: Deployment Cancelled!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}